name: Run Integration Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      run: nuget restore Software/EventManager/EventManager.sln

    - name: Build
      run: msbuild Software/EventManager/EventManager.sln /p:Configuration=Release
      
    - name: Run Integration Tests
      run: dotnet test Software/EventManager/EventManager_IntegrationTests/EventManager_IntegrationTests.csproj --no-build --configuration Release --logger "trx;LogFileName=Integration_tests_results.trx"

